name: alpha_french_fries
description: "2 Bit Alu GUI"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.11.2
  flutter_svg: ^2.0.17
  flutter_blue_classic: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter_native_splash:
  background_image: "assets/meta/splash_back.png"
  background_image_dark: "assets/meta/splash_back_dark.png"
  image: assets/meta/icon.png
  android_screen_orientation: userLandscape
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/led_off.svg
    - assets/led_on.svg
